spring:
  application:
    name: online_store
  datasource:
    url: jdbc:postgresql://localhost:5432/online_store
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: post260125DiMa
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

server:
  port: 8081

aws:
  s3:
    bucket: my-online-store-bucket
    region: eu-north-1

app:
  api:
    uriPrefix: /api/v1
  sku:
    padding: 8